services:
  - type: web
    name: hotel-room-strapi
    runtime: node
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /_health
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PROXY_TRUST
        value: "true"
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_SSL
        value: "true"
      - key: DATABASE_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
